### ISSUE TITLE
auth.py下的# test = 1 / 0加的真的好恶心

### ISSUE THREAD

**Issue by xiaoyue2019** [eugene-afk/flask-mini-cms#2]
不知道作者是为了测试还是干嘛，
但一直登不上，需要把auth.py下的21行： test = 1 / 0注释了

难受，搞了一上午，擦

**Comment by eugene-afk** [comment]
Hello, xiaoyue2019, I'm sorry for this, I tested logger and forget to remove this line. Thanks for your attentiveness and next time it would be better if you will write in English, so I can understand you faster and properly.
